server:
  port: 52001
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    #statusPageUrlPath: /info
    #healthCheckUrlPath: /health
    #hostname: 127.0.0.1
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:52002/eureka/

